Milestone 2 Portfolio: Mobile version
mavericks-db/portfolio pull request #2
Opened 2022-03-17 15:31 UTC by mavericks-db

## Mobile version
-replace icon bar with inline svg
-add svg hover effect
-add work and about me section

2022-03-17 18:14 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @mavericks-db👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

## Required Changes ♻️

- [ ] To make your README file more professional, Please add other sections like acknowledgment, getting started. You can use this [template](https://github.com/microverseinc/readme-template) but customize it for your project.

- [ ] Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 18:14 UTC, thecodechaser commented on index.html
> +            <h4>HTML</h4>
- [ ] You did a very good job with the style but for this project, you are supposed to stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988) as much as possible. Please use correct background-color for technologies `background-color: #EBF0EE;`

2022-03-17 18:14 UTC, thecodechaser commented on index.html
> +  </section>
- [ ] Please fix the background images for the about section, They are overflowing on content.

### Your design

![image](https://user-images.githubusercontent.com/83803414/158867290-c4719980-df00-4817-a90e-4c68bd0e4ce3.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/158867330-b4ff3512-c8fd-4ffe-bb60-90a436f68423.png)

2022-03-18 04:38 UTC, CollinsTatang approved these changes
Hi @mavericks-db, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
### **OPTIONAL CHANGES**

- [x] Kindly fix your list of technologies to be as on the design.
**Your Design**
![fixButton](https://user-images.githubusercontent.com/55596970/158937923-7d013e9a-5afa-4553-918f-4b531795efe4.png)
**Figmal Design**
![checks](https://user-images.githubusercontent.com/55596970/158938269-1bd25546-f125-4b85-a9cc-feb12a48da3c.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 05:16 UTC, merged